# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 604ae9b37f1e2bc7e2fac55d63ad331e69a23e235a205a0f2a29852d17cb37309292142f3633e29bdf61255c475ab70873bde0fdf942b9fb157b8dc9211f8411

test:
  secret_key_base: 1879720c1141117159cd30a79516c3f5ffce088b4797b858d703bbe120011e50fdc1b26ae72af1d676a290e4ea43816f66ebd3e38daceeb7533016bc71ccdd25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
